# Generated by Django 5.1.5 on 2025-01-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewai_agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('config', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='agent',
            name='tools',
        ),
        migrations.AddField(
            model_name='agent',
            name='tools',
            field=models.ManyToManyField(blank=True, null=True, related_name='agents', to='crewai_agents.tool'),
        ),
    ]
