# Generated by Django 5.1.5 on 2025-01-25 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewai_agents', '0004_remove_tool_config_tool_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorTrend',
            fields=[
                ('trend_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('source', models.CharField(max_length=200)),
                ('trend_description', models.TextField()),
                ('competitor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('impact_level', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuccessMetric',
            fields=[
                ('case_study_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=100)),
                ('program_description', models.TextField()),
                ('roi', models.FloatField(blank=True, null=True)),
                ('productivity_gains', models.FloatField(blank=True, null=True)),
                ('employee_retention', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='last_updated',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='company',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='priority_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='revenue_growth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='stress_level_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='wellness_culture_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactperson',
            name='last_contact_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactperson',
            name='linkedin_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactperson',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactperson',
            name='preferred_contact_method',
            field=models.CharField(choices=[('Email', 'Email'), ('Phone', 'Phone'), ('LinkedIn', 'LinkedIn')], default='Email', max_length=50),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.CreateModel(
            name='Outreach',
            fields=[
                ('outreach_id', models.AutoField(primary_key=True, serialize=False)),
                ('outreach_date', models.DateField(auto_now_add=True)),
                ('outreach_method', models.CharField(choices=[('Email', 'Email'), ('LinkedIn', 'LinkedIn Message'), ('Phone', 'Phone Call')], max_length=50)),
                ('template_used', models.TextField()),
                ('response_status', models.CharField(choices=[('No Response', 'No Response'), ('Interested', 'Interested'), ('Not Interested', 'Not Interested')], default='No Response', max_length=50)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach_attempts', to='crewai_agents.contactperson')),
            ],
        ),
    ]
