# Generated by Django 5.1.5 on 2025-01-26 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewai_agents', '0005_competitortrend_successmetric_company_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='context',
            field=models.ManyToManyField(blank=True, related_name='dependent_tasks', to='crewai_agents.task'),
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_name', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crewai_agents.task')),
            ],
        ),
    ]
