# Generated by Django 5.1.5 on 2025-01-26 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crewai_agents', '0007_alter_task_options_task_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkflowStep',
        ),
    ]
