# Generated by Django 5.1.5 on 2025-01-26 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewai_agents', '0008_delete_workflowstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreach',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outreach_company', to='crewai_agents.company'),
        ),
    ]
