# Generated by Django 5.1.5 on 2025-01-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewai_agents', '0009_outreach_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outreach',
            name='template_used',
        ),
        migrations.AddField(
            model_name='outreach',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='outreach',
            name='message_type',
            field=models.CharField(choices=[('Email', 'Email'), ('LinkedIn', 'LinkedIn Message'), ('Phone', 'Phone Call')], default='Email', max_length=50),
        ),
    ]
