# Generated by Django 5.1.5 on 2025-01-26 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crewai_agents', '0010_remove_outreach_template_used_outreach_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outreach',
            old_name='notes',
            new_name='comments',
        ),
        migrations.RemoveField(
            model_name='outreach',
            name='outreach_method',
        ),
    ]
