# Generated by Django 5.1.5 on 2025-01-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewai_agents', '0011_rename_notes_outreach_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outreach',
            name='outreach_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='response_status',
            field=models.CharField(choices=[('awaiting', 'Awaiting Response'), ('Interested', 'Interested'), ('No Response', 'No Response'), ('Not Interested', 'Not Interested')], default='No Response', max_length=50),
        ),
    ]
