# Generated by Django 5.1.5 on 2025-01-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewai_agents', '0012_alter_outreach_outreach_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outreach',
            name='contact',
        ),
        migrations.AlterField(
            model_name='outreach',
            name='comments',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='follow_up_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='outreach',
            name='message',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
