# Generated by Django 5.1.5 on 2025-01-27 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewai_agents', '0013_remove_outreach_contact_alter_outreach_comments_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SuccessMetric',
        ),
        migrations.AlterField(
            model_name='competitortrend',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='competitortrend',
            name='trend_description',
            field=models.TextField(default=''),
        ),
    ]
