# Generated by Django 5.1.5 on 2025-01-30 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewai_agents', '0015_alter_outreach_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_employees', models.IntegerField(help_text='Minimum number of employees for this tier.')),
                ('max_employees', models.IntegerField(help_text='Maximum number of employees for this tier.')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price for this tier.', max_digits=10)),
                ('features', models.TextField(blank=True, help_text='Features included in this tier.', null=True)),
            ],
            options={
                'ordering': ['min_employees'],
            },
        ),
    ]
