# Generated by Django 5.1.5 on 2025-02-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewai_agents', '0016_pricingtier'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('calendar_invite', 'Calendar Meeting Invite'), ('meeting_confirmed', 'Meeting Confirmation'), ('reschedule', 'Reschedule Request')], default='calendar_invite', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Available variables: {calendar_link}, {recipient_name}, {meeting_duration}')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='decision_makers',
            field=models.JSONField(blank=True, default=list, help_text='\n        List of contact persons in format:\n        [\n            {\n                "name": "string",\n                "role": "string",\n                "email": "email@example.com",\n                "phone": "string",\n                "linkedin_profile": "url",\n                "preferred_contact": "Email|Phone|LinkedIn",\n                "last_contact_date": "YYYY-MM-DD",\n                "notes": "string"\n            }\n        ]\n    '),
        ),
    ]
