# Generated by Django 5.1.5 on 2025-02-20 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewai_agents', '0017_emailtemplate_company_decision_makers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outreach',
            name='follow_up_date',
        ),
        migrations.RemoveField(
            model_name='outreach',
            name='message',
        ),
        migrations.RemoveField(
            model_name='outreach',
            name='message_type',
        ),
        migrations.RemoveField(
            model_name='outreach',
            name='response_status',
        ),
        migrations.AddField(
            model_name='outreach',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outreach_email', to='crewai_agents.emailtemplate'),
        ),
    ]
