# Generated by Django 5.1.5 on 2025-02-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewai_agents', '0018_remove_outreach_follow_up_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreach',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Email Sent'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
