# Generated by Django 5.1.5 on 2025-02-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewai_agents', '0020_rename_emailtemplate_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
    ]
