# Generated by Django 5.1.5 on 2025-02-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewai_agents', '0021_email_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='recipient',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
