# Generated by Django 5.1.5 on 2025-02-22 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crewai_agents', '0022_email_recipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='type',
        ),
    ]
