# Generated by Django 5.1.5 on 2025-02-23 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewai_agents', '0024_alter_company_options_alter_email_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='callback',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='output_json',
            field=models.BooleanField(default=False),
        ),
    ]
