# Generated by Django 5.1.5 on 2025-02-24 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crewai_agents', '0025_task_callback_task_output_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='callback',
        ),
        migrations.RemoveField(
            model_name='task',
            name='output_json',
        ),
    ]
