# Generated by Django 5.1.6 on 2025-02-26 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewai_agents', '0027_agentconfig_agentlog_toolconfig_remove_agent_tools_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
