# Generated by Django 5.1.6 on 2025-02-26 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewai_agents', '0028_company_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='outreach',
            name='created_at',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
