# Generated by Django 5.1.6 on 2025-02-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewai_agents', '0029_outreach_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outreach',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
