# Generated by Django 5.1.6 on 2025-02-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewai_agents', '0030_alter_outreach_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('stopped', 'Stopped'), ('running', 'Running')], default='stopped', max_length=10)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Script Status',
                'verbose_name_plural': 'Script Status',
            },
        ),
    ]
